### ISSUE TITLE
Magento doesn't see images

### ISSUE THREAD

**Issue by dgallegos** [bangerkuwranger/magento2-google-cloud-storage#2]
Magento 2.1.5

I can 'Synchronize' and get images up to Google Cloud, but I can't get my server to use those images once I set my "Media Storage" to Google Cloud.

**Comment by ChaerilM** [comment]
@dgallegos have you found the fix?

**Comment by ram10raj** [comment]
Get the image public url  google cloud and use that url in  media path

**Comment by caedlesu** [comment]
> Get the image public url google cloud and use that url in media path

Where do I set that? the Module already uploaded the images but I can't start using them.
