### ISSUE TITLE
Images are not being uploaded directly on GCS

### ISSUE THREAD

**Issue by pareshpa** [bangerkuwranger/magento2-google-cloud-storage#3]
There is an issue when I upload the category image from Admin and images are not getting uploaded on GCS. Instead, it stores on file system.

**Comment by ram10raj** [comment]
It's not direct sync you have manually sync to cloud.

**Comment by gauravjos** [comment]
Does manual sync is possible through cmdline ?

**Comment by ram10raj** [comment]
yes we use command line sync also 

php bin/magento gcs:storage:sync
