### ISSUE TITLE
Problem with synchronization files

### ISSUE THREAD

**Issue by ivanko-dev** [bangerkuwranger/magento2-google-cloud-storage#4]
I am using Magento 2.1.7 installed on Bitnami Magento For Google Cloud Platform. Magento working right now in development mode with switched off caching.
When I am trying to update Media Storage to Google Cloud platform I am getting long time loading with only two files from root folder placed in web root folder.

When I am trying to implement synchronization using shell command php bin/magento gcs:storage:sync
Then I am getting message Uploading files to use GCS, long loading, same two files uploaded and then error message

PHP Fatal error:  Uncaught Error: Call to undefined method Google\Cloud\Exception\GoogleException::getServiceException() in /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php:229
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php(205): cAc\GcsWrapper\GoogleCloudStorage->bucket_upload_directory('app/')
#1 /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php(205): cAc\GcsWrapper\GoogleCloudStorage->bucket_upload_directory('app/')
#2 /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php(205): cAc\GcsWrapper\GoogleCloudStorage->bucket_upload_directory('app/')
#3 /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php(205): cAc\GcsWrapper\GoogleCloudStorage->bucket_upload_directory('app/')
#4 /opt/bitnami/apps/magento/htdocs/v in /opt/bitnami/apps/magento/htdocs/vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php on line 229

Could you please help to find out what is wrong there?

**Comment by ram10raj** [comment]
Did you changed the media storage  as google cloud ?
then save the configuration after that do the command line sync.
if still exist let me know we will fix that issue

Thanks,

**Comment by ivanko-dev** [comment]
Thank you for response and sorry for long time no information about this issue.

Now we have Magento 2.2.0 and I have tried all these steps and then made quick debug what happen in application.
So this is what was done:

1. Set up configuration in Admin panel -> Stores -> (Settings) Configuration -> (Google Cloud Storage) Google Cloud
2. Set up storage in Admin panel -> Stores -> (Settings) Configuration -> (Advanced) System -> Storage Configuration for Media:
- changed Media Storage to Google Cloud Storage
- run Synchronize action

After this steps: long time loading and regular ajax requests in browser to http://mydomain.test/admin/admin/system_config_system_storage/status/?isAjax=true&&form_key=wOgdYwI1ftD12Mda
First responses for this requests was:
{"message":"Synchronizing File system to Google Cloud Storage","state":"1"}
And some content of my pub/media was uploaded to GCS bucket

Then after some time returned:
{"has_errors":true,"state":2}
And stopped uploading.

After these steps I was able to save current Storage Configuration for Media and haven't found any logs about exception in Magento logs and apache logs. Maybe this issue cause by many files in media folder (around 1995 files there).

Next step was run of console command: php bin/magento gcs:storage:sync
And seems here is some issue with path for uploading. After command run files and folders from Magento application root folder was uploaded to GCS. After quick debug I have seen that  $dir_files = glob( '*', GLOB_MARK ); (vendor/bangerkuwranger/google-cloud-storage-php-wrapper/GoogleCloudStorage.php : Line 198) always read files from application root folder and it is always same files even it try to read subfolder recursively.

I have few ideas how to resolve this issue with using path in glob and update filename before upload to get relative path on save at GCS but I would like ask you about this issue. Maybe this is something wrong with configuration or implemented steps.

Could you please help to find out solution for our case?
Thanks in advance.

**Comment by caedlesu** [comment]
I was able to sync my files to the google storage bucket, but magento is still using the local url for the images, have you been able to find a solution for your issue? I don't know how to set magento to use the GCS link instead of the local path.

**Comment by ivanko-dev** [comment]
@caedlesu, please take a look on Stores -> Configuration -> General (tab) -> Web and there you can find setting for Base URLs (secure or not secure based on your application configuration). You can set there link to your GCS bucket and load data directly from cloud. Data in bucket should be available for public read access in this case.
Are you getting your data updated after synchronization? In my case I was not able to get this so used another services for handling static and media data in Magento.

**Comment by caedlesu** [comment]
@ivan-koliadynskyy thanks for your response, so in the base urls I should place the google storage bucket link, right? and yeah my data's being updated in the bucket after the sync.
Also the module is not creating the pub/media folder and I saw in the code that is a plugin that is doing that, should I remove that option? can you help me by giving me an example of the link I should place for the base url.
Thanks.

**Comment by ram10raj** [comment]
@caedlesu , You need to change media in the general tab with google cloud url
