### ISSUE TITLE
composer require bangerkuwranger/magento2-google-cloud-storage hint error

### ISSUE THREAD

**Issue by robert-damon** [bangerkuwranger/magento2-google-cloud-storage#6]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bangerkuwranger/magento2-google-cloud-storage 1.0.1 requires bangerkuwranger/google-cloud-storage-php-wrapper dev-master -> satisfiable by bangerkuwranger/google-cloud-storage-php-wrapper[dev-master] but these conflict with your requirements or minimum-stability.
    - bangerkuwranger/magento2-google-cloud-storage 1.0.0 requires bangerkuwranger/google-cloud-storage-php-wrapper dev-master -> satisfiable by bangerkuwranger/google-cloud-storage-php-wrapper[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for bangerkuwranger/magento2-google-cloud-storage ^1.0 -> satisfiable by bangerkuwranger/magento2-google-cloud-storage[1.0.0, 1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by ram10raj** [comment]
@Robert-Damon  : something  related to installation please share skype id i can help us.

**Comment by thanandorn** [comment]
@ram10raj Has the issue been resolved? If so, can you please share the information. I'm hitting the same issue.

**Comment by thanandorn** [comment]
The module seems to require `[master]` branch of "bangerkuwranger/google-cloud-storage-php-wrapper" as a dependency https://github.com/bangerkuwranger/magento2-google-cloud-storage/blob/v1.0.1/composer.json#L27

Here are my workaround steps.

```
composer config repositories.1 "git" "https://github.com/bangerkuwranger/google-cloud-storage-php-wrapper.git" 
composer require bangerkuwranger/google-cloud-storage-php-wrapper:dev-master
composer require bangerkuwranger/magento2-google-cloud-storage
```

The above works for me. I am no PHP or Magento expert. If anyone can prove that my workaround is not the right way, I'd be happy to take advices.
