### ISSUE TITLE
Images are not directly upload on Google Cloud

### ISSUE THREAD

**Issue by PHPManager133** [bangerkuwranger/magento2-google-cloud-storage#8]
I am facing this issue http://prntscr.com/ibt4jd while sync the media on GCS. can you please provide the solution of it. And also can you please confirm me that this extension can also upload the images directly to GCS when we create the new product and update the path on Database ?

Thanks
Sukhbir

**Comment by PHPManager133** [comment]
I have checked that the above issue is coming due to this issue:

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'cAc\GcsWrapper\GoogleCloudStorage' not found in /var/www/html/grooger/app/code/Google/Cloud/Model/MediaStorage/File/Storage/Gcs.php:70
Stack trace:
#0 /var/www/html/grooger/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Google\Cloud\Model\MediaStorage\File\Storage\Gcs-&gt;__construct(Object(Google\Cloud\Helper\Data), Object(Magento\MediaStorage\Helper\File\Media), Object(Magento\MediaStorage\Helper\File\Storage\Database\Interceptor), Object(Magento\Framework\Logger\Monolog), Object(Magento\MediaStorage\Model\File\Storage\File))
#1 /var/www/html/grooger/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory-&gt;createObject('Google\\Cloud\\Mo...', Array)
#2 /var/www/html/grooger/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer-&gt;create('Google\\Cloud\\Mo...', Array)
#3 /var/www/html/grooger/var/generation/Google/Cloud/Model/Me in <b>/var/www/html/grooger/app/code/Google/Cloud/Model/MediaStorage/File/Storage/Gcs.php</b> on line <b>70</b><br />

Can you please look this issue and let me know the solution for it.

Thanks

**Comment by ram10raj** [comment]
@PHPManager133  -Dependencies not installed properly .
