### ISSUE TITLE
 \cAc\GcsWrapper\GoogleCloudStorage Class missing

### ISSUE THREAD

**Issue by kishoreacharya** [bangerkuwranger/magento2-google-cloud-storage#9]
PHP Fatal error:  Uncaught Error: Class 'cAc\GcsWrapper\GoogleCloudStorage' not found 

I'm facing above error that GoogleCloudStorage Class not found. Please help me with this issue.

**Comment by kishoreacharya** [comment]
have fixed this issue

**Comment by tuananh8127** [comment]
Fatal error: Uncaught Error: Class 'cAc\GcsWrapper\GoogleCloudStorage' not found
Please help me.

**Comment by alexvais** [comment]
@kishoreacharya how you fix it?
